### ISSUE TITLE
bug: you can increase the guess count while the animation is still playing

### ISSUE THREAD

**Issue by LeoDog896** [willuhmjs/hintable#4]
To reproduce:
1. Open the website
2. Start spamming letters into the input

**Comment by willuhmjs** [comment]
Okay, I will fix it in a future commit.

**Comment by willuhmjs** [comment]
Fixed in commit [3eb5592](https://github.com/willuhmjs/hintable/commit/3eb5592f184224c453012e8269c25888a5dca4dc).
